# Generated by Django 4.0.1 on 2022-01-11 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RiskGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistiche',
            name='NicknameGiocatore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='RiskGame.giocatoreregistrato'),
        ),
    ]
