# Generated by Django 4.0.1 on 2022-01-20 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RiskGame', '0002_alter_statistiche_nicknamegiocatore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistiche',
            name='NicknameGiocatore',
        ),
        migrations.AddField(
            model_name='statistiche',
            name='IDGiocatore',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mappa',
            name='Autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partita',
            name='Giocatori',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
