# Generated by Django 4.0.1 on 2022-01-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiskGame', '0003_remove_statistiche_nicknamegiocatore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorio',
            name='Confini',
            field=models.ManyToManyField(to='RiskGame.Territorio'),
        ),
        migrations.AlterField(
            model_name='territorio',
            name='NomeTerritorio',
            field=models.CharField(max_length=20),
        ),
    ]
