# Generated by Django 4.0.1 on 2022-01-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiskGame', '0003_remove_statistiche_nicknamegiocatore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorio',
            name='Confini',
            field=models.ManyToManyField(blank=True, to='RiskGame.Territorio'),
        ),
    ]
