# Generated by Django 4.0.1 on 2022-01-26 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RiskGame', '0003_remove_statistiche_nicknamegiocatore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ospite',
            fields=[
                ('Nickname', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('Assegnato', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='GiocatoreRegistrato',
        ),
        migrations.AddField(
            model_name='mappa',
            name='Difficolta',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='territorio',
            name='Confini',
            field=models.ManyToManyField(blank=True, to='RiskGame.Territorio'),
        ),
        migrations.AddField(
            model_name='territorio',
            name='Mappa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RiskGame.mappa'),
        ),
        migrations.AlterField(
            model_name='territorio',
            name='NomeTerritorio',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='partita',
            name='Ospiti',
            field=models.ManyToManyField(to='RiskGame.Ospite'),
        ),
    ]
