# Generated by Django 4.0.1 on 2022-01-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiskGame', '0004_territorio_confini_alter_territorio_nometerritorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territorio',
            name='Confini',
            field=models.ManyToManyField(blank=True, to='RiskGame.Territorio'),
        ),
    ]
