# Generated by Django 4.0.1 on 2022-01-27 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RiskGame', '0004_ospite_delete_giocatoreregistrato_mappa_difficolta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappa',
            name='Autore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
