# Generated by Django 4.0.1 on 2022-01-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiskGame', '0004_territorio_confini'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappa',
            name='Difficoltà',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
