# Generated by Django 4.0.1 on 2022-01-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiskGame', '0005_alter_territorio_confini'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ospite',
            fields=[
                ('Nickname', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('Assegnato', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='GiocatoreRegistrato',
        ),
        migrations.AddField(
            model_name='partita',
            name='Ospiti',
            field=models.ManyToManyField(to='RiskGame.Ospite'),
        ),
    ]
