# Generated by Django 4.0.1 on 2022-01-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiskGame', '0005_mappa_difficoltà'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappa',
            name='Difficoltà',
        ),
    ]
