# Generated by Django 4.0.1 on 2022-01-27 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiskGame', '0006_ospite_delete_giocatoreregistrato_mappa_difficolta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continente',
            name='Colore',
        ),
    ]
