# Generated by Django 4.0.1 on 2022-01-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiskGame', '0007_remove_continente_colore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistiche',
            name='TempoDiGioco',
            field=models.TimeField(null=True),
        ),
    ]
