# Generated by Django 4.0.1 on 2022-01-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiskGame', '0007_mappa_difficoltà'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappa',
            name='Difficoltà',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
