# Generated by Django 4.0.1 on 2022-01-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiskGame', '0008_alter_statistiche_tempodigioco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistiche',
            name='NumeroTruppeGenerate',
        ),
        migrations.RemoveField(
            model_name='statistiche',
            name='NumeroTruppePerse',
        ),
        migrations.RemoveField(
            model_name='statistiche',
            name='TempoDiGioco',
        ),
    ]
