# Generated by Django 4.0.1 on 2022-01-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiskGame', '0008_alter_mappa_difficoltà'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappa',
            name='Difficoltà',
        ),
        migrations.AddField(
            model_name='mappa',
            name='Difficolta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
