# Generated by Django 4.0.1 on 2022-01-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiskGame', '0009_remove_mappa_difficoltà_mappa_difficolta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappa',
            name='Difficolta',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
