# Generated by Django 4.0.1 on 2022-01-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiskGame', '0010_alter_mappa_difficolta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappa',
            name='Difficolta',
            field=models.CharField(default='', max_length=20),
        ),
    ]
