# Generated by Django 4.0.1 on 2022-01-26 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RiskGame', '0011_alter_mappa_difficolta'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorio',
            name='Mappa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RiskGame.mappa'),
        ),
    ]
